class MudisClient
  SOCKET_PATH: String

  def initialize: () -> void

  def request: (payload: { cmd: String, key?: String, value?: untyped, ttl?: Integer?, namespace?: String? }) -> untyped

  def read: (key: String, namespace?: String?) -> untyped

  def write: (key: String, value: untyped, expires_in?: Integer?, namespace?: String?) -> untyped

  def delete: (key: String, namespace?: String?) -> untyped

  def exists?: (key: String, namespace?: String?) -> bool

  def fetch: (key: String, expires_in?: Integer?, namespace?: String?, &block: { () -> untyped }) -> untyped

  def metrics: () -> { reads: Integer, writes: Integer, deletes: Integer, exists: Integer }

  def reset_metrics!: () -> void

  def reset!: () -> void
end