class MudisClient
  include MudisIPCConfig

  def initialize: () -> void

  def open_connection: () -> (TCPSocket | UNIXSocket)

  def request: (payload: Hash[Symbol, untyped]) -> untyped

  def read: (key: String, namespace?: String?) -> untyped

  def write: (key: String, value: untyped, expires_in?: Integer?, namespace?: String?) -> untyped

  def delete: (key: String, namespace?: String?) -> untyped

  def exists?: (key: String, namespace?: String?) -> bool

  def fetch: (key: String, expires_in?: Integer?, namespace?: String?, &block: { () -> untyped }) -> untyped

  def inspect: (key: String, namespace?: String?) -> Hash[Symbol, untyped]?

  def keys: (namespace: String) -> Array[String]

  def clear_namespace: (namespace: String) -> void

  def least_touched: (?Integer) -> Array[[String, Integer]]

  def all_keys: () -> Array[String]

  def current_memory_bytes: () -> Integer

  def max_memory_bytes: () -> Integer

  def metrics: () -> Hash[Symbol, untyped]
end
