class MudisClient
  include MudisIPCConfig

  def initialize: () -> void

  def open_connection: () -> (TCPSocket | UNIXSocket)

  def request: (payload: Hash[Symbol, untyped]) -> untyped

  def read: (key: String, namespace?: String?) -> untyped

  def write: (key: String, value: untyped, expires_in?: Integer?, namespace?: String?) -> untyped

  def delete: (key: String, namespace?: String?) -> untyped

  def exists?: (key: String, namespace?: String?) -> bool

  def fetch: (key: String, expires_in?: Integer?, namespace?: String?, &block: { () -> untyped }) -> untyped

  def metrics: () -> Hash[Symbol, untyped]

  def reset_metrics!: () -> void

  def reset!: () -> void
end
