class MudisConfig
  attr_accessor serializer: Object
  attr_accessor compress: bool
  attr_accessor max_value_bytes: Integer?
  attr_accessor hard_memory_limit: bool
  attr_accessor max_bytes: Integer
  attr_accessor eviction_threshold: Float?
  attr_accessor max_ttl: Integer?
  attr_accessor default_ttl: Integer?
  attr_accessor buckets: Integer?
  attr_accessor persistence_enabled: bool
  attr_accessor persistence_path: String
  attr_accessor persistence_format: Symbol
  attr_accessor persistence_safe_write: bool
end
